name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install stable toolchain
      run: rustup default nightly
    - name: Install clippy
      run: rustup component add clippy
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy linting
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
